name: 'Demeter CLI installer'
description: 'Install a specific version of dmtrctl binary'
inputs:
  version:
    description: 'Version of dmtrctl to install. Leave empty for latest.'
    required: false
    default: 'stable'
outputs:
  dmtrctl-path:
    description: 'Path to the cached dmtrctl binary'
runs:
  using: 'node20'
  main: 'lib/index.js'